name: APK Build

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Dispatch to `customer-app`
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOUFEEQ_PERSONAL_ACCESS_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'toufeeq-refyne',
              repo: 'flutter-injectable-tutorial-copy',
              event_type: 'on_core_server_push',
            });
